<?php
// Home pública: apresenta a academia, unidades, planos e links de acesso.
require_once __DIR__ . '/conexao.php';
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iron Fit | Academia</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/index.css">
</head>
<body class="public-home">
    <header class="public-header"><nav class="navbar navbar-expand-lg navbar-dark"><div class="container"><a class="navbar-brand logo" href="index.php">IRON FIT</a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#publicNav" aria-label="Abrir menu"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-3"><li class="nav-item"><a class="nav-link" href="#sobre">Sobre</a></li><li class="nav-item"><a class="nav-link" href="#modalidades">Modalidades</a></li><li class="nav-item"><a class="nav-link" href="#unidades">Unidades</a></li><li class="nav-item"><a class="nav-link" href="#planos">Planos</a></li><li class="nav-item"><a class="nav-link" href="#contato">Contato</a></li><li class="nav-item"><a class="btn btn-outline-danger" href="pages/acesso.php">Entrar</a></li></ul></div></div></nav></header>
    <main>
        <section class="public-hero"><div class="container public-hero-content"><p class="eyebrow">FORÇA. FOCO. CONSTÂNCIA.</p><h1>Seu próximo nível começa aqui.</h1><p class="lead">Treino inteligente, estrutura completa e uma comunidade que ajuda você a evoluir todos os dias.</p><div class="d-flex flex-wrap gap-3"><a class="btn btn-danger btn-lg" href="#planos">Conheça os planos</a><a class="btn btn-light btn-lg" href="pages/criar.php">Começar agora</a></div></div></section>
        <section id="sobre" class="public-section"><div class="container"><div class="row g-4 align-items-center"><div class="col-lg-7"><p class="eyebrow">IRON FIT</p><h2>Treinar bem muda a forma como você vive.</h2><p class="section-copy">Na Iron Fit, você encontra equipamentos modernos, orientação qualificada e um ambiente feito para transformar consistência em resultado.</p></div><div class="col-lg-5"><div class="stat-grid"><div><strong>24/7</strong><span>energia para treinar</span></div><div><strong>+3</strong><span>modalidades</span></div><div><strong>100%</strong><span>foco em você</span></div></div></div></div></div></section>
        <section id="modalidades" class="public-section dark-band"><div class="container"><div class="section-heading"><p class="eyebrow">ESTRUTURA COMPLETA</p><h2>Treine do seu jeito</h2></div><div class="public-grid"><article><span class="feature-number">01</span><h3>Musculação</h3><p>Equipamentos para todos os objetivos, do primeiro treino à alta performance.</p></article><article><span class="feature-number">02</span><h3>Funcional</h3><p>Movimento, condicionamento e aulas dinâmicas para sair da rotina.</p></article><article><span class="feature-number">03</span><h3>Acompanhamento</h3><p>Profissionais preparados para orientar seu treino com mais segurança.</p></article></div></div></section>
        <section id="unidades" class="public-section locations-section"><div class="container"><div class="section-heading"><p class="eyebrow">CHEGUE MAIS PERTO</p><h2>Uma Iron Fit perto de você</h2><p class="section-copy">Escolha a unidade que combina com sua rotina e venha treinar com a gente.</p></div><div class="locations-grid"><article class="location-card"><div class="location-image location-center"></div><div class="location-content"><span>São Paulo</span><h3>Unidade Centro</h3><p>Treine no coração da cidade, com estrutura completa e fácil acesso.</p><a href="https://www.google.com/maps?q=S%C3%A3o%20Paulo&output=search" target="_blank" rel="noopener">Ver localização ↗</a></div></article><article class="location-card"><div class="location-image location-south"></div><div class="location-content"><span>Rio de Janeiro</span><h3>Unidade Zona Sul</h3><p>Um espaço amplo para manter seu ritmo todos os dias.</p><a href="https://www.google.com/maps?q=Rio%20de%20Janeiro&output=search" target="_blank" rel="noopener">Ver localização ↗</a></div></article><article class="location-card"><div class="location-image location-shopping"></div><div class="location-content"><span>Belo Horizonte</span><h3>Unidade Shopping</h3><p>Praticidade para encaixar o treino na sua agenda.</p><a href="https://www.google.com/maps?q=Belo%20Horizonte&output=search" target="_blank" rel="noopener">Ver localização ↗</a></div></article></div><div class="text-center mt-4"><a class="btn btn-outline-danger" href="pages/unidades.php">Conheça todas as unidades</a></div></div></section>
        <section id="planos" class="public-section"><div class="container"><div class="section-heading"><p class="eyebrow">ESCOLHA SEU RITMO</p><h2>Planos para continuar evoluindo</h2></div><div class="public-grid plans-public"><?php $planos = $conn->query('SELECT * FROM planos ORDER BY valor ASC LIMIT 3'); while ($plano = $planos ? $planos->fetch_assoc() : null): ?><article class="plan-public"><h3><?= htmlspecialchars($plano['nome']) ?></h3><p><?= htmlspecialchars($plano['descricao']) ?></p><strong>R$ <?= number_format((float) $plano['valor'], 2, ',', '.') ?></strong><a href="pages/criar.php">Quero este plano</a></article><?php endwhile; ?></div></div></section>
        <section id="contato" class="public-section contact-band"><div class="container"><div class="row g-4"><div class="col-md-4"><p class="eyebrow">VISITE A IRON FIT</p><h2>Pronto para começar?</h2></div><div class="col-md-4"><h3>Horários</h3><p>Segunda a sexta: 06h às 23h<br>Sábado: 08h às 18h</p></div><div class="col-md-4"><h3>Fale com a gente</h3><p>(11) 99999-0000<br>contato@ironfit.com</p></div></div></div></section>
    </main>
    <footer class="public-footer"><div class="container d-flex flex-wrap justify-content-between gap-3"><span>IRON FIT</span><span>Treine mais forte. Viva melhor.</span><span>© <?= date('Y') ?> Iron Fit</span></div></footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
